use dir_writer::{FileCollector, GeneratorArgs, LanguageFeatures};
use internal_baml_core::ir::repr::IntermediateRepr;
use std::sync::Arc;

mod metadata_schema;
mod ir_to_metadata;

#[derive(Default)]
pub struct CSharpMetadataLanguageFeatures;

impl LanguageFeatures for CSharpMetadataLanguageFeatures {
    const CONTENT_PREFIX: &'static str = r#"// This file was generated by BAML: please do not edit it.
// This metadata can be consumed by C# source generators to create the actual implementation.
// Format version: 1.0.0
"#;

    fn name() -> &'static str {
        "csharp/metadata"
    }

    fn generate_sdk_files(
        &self,
        collector: &mut FileCollector<Self>,
        ir: Arc<IntermediateRepr>,
        _args: &GeneratorArgs,
    ) -> Result<(), anyhow::Error> {
        let metadata = metadata_schema::CSharpMetadata::from_ir(ir.as_ref());

        // Generate JSON metadata only
        let json_output = serde_json::to_string_pretty(&metadata)?;
        collector.add_file("baml-metadata.json", json_output)?;

        Ok(())
    }
}

#[cfg(test)]
mod csharp_metadata_tests {
    use test_harness::{create_code_gen_test_suites, TestLanguageFeatures};

    impl TestLanguageFeatures for crate::CSharpMetadataLanguageFeatures {
        fn test_name() -> &'static str {
            "csharp-metadata"
        }
    }

    create_code_gen_test_suites!(crate::CSharpMetadataLanguageFeatures);
}
